### ISSUE TITLE
Signed Releases

### ISSUE THREAD

**Issue by quantumpacket** [mtorromeo/r8168#18]
Can we please have signed releases? A signed checksums file with the hashes for the release and source would be great. An end-user can't assume that data integrity has been preserved on an untrusted 3rd party platform, especially for something that is going to be the source of network access for their system. Thank you for your time and your hard work.

**Comment by ratijas** [comment]
Also, PGP-signed commits wouldn't hurt!

I wonder, why did you self-close the issue, @quantumpacket?

**Comment by quantumpacket** [comment]
@ratijas I closed it because I no longer use this module and this issue just fell victim to my periodic open tickets cleanup. :P

I shall reopen.

**Comment by mtorromeo** [comment]
I can sign both releases and commits but you should be aware of the fact that I do not work, represent, or am endorsed by Realtek

**Comment by ratijas** [comment]
It would be extremely cool of you, @mtorromeo! Thanks. We, lazy end users, entrust you with our systems, so that we no longer suffer from that stupid email capcha of Realtek :slightly_smiling_face: 

BTW, I think, the fact that you are not a representative is very well conveyed by the annotation _unofficial mirror_ in repository's About section.

**Comment by mtorromeo** [comment]
Alright, I signed the last release, and future commits will be signed as well.
