### ISSUE TITLE
create community branch 

### ISSUE THREAD

**Issue by gamegine** [mtorromeo/r8168#50]
hello, I have been using this repository for some time and I am still trying to solve my problem with this driver, I understand that this repository is intended to be a mirror of official sources, but the community often offers improvements and bugfixes like #43 Add support to device or #47 Adapted for Linux 6.1 , I suggest so create a second branch 'community' to welcome them and leave the master branch as a mirror of the official versions

**Comment by mtorromeo** [comment]
While I understand the need for a place to gather useful patches and improvements to this driver, I won't create a branch in this repo for that purpose.

Applying patches to a separate branch is easy enough at first, but the more patches get accepted, the more the branch will start diverging from upstream and a with each official new release there will be work that needs to be done to either merge the changes or rebase the branch, which is never a good idea for a branch that will need to be tracked by other developers and receive more patches.

I don't think that's an unreasonable amount of work, but it should be done by someone with an interest in improving the driver, and I am not that person also because I don't even have hardware that needs this driver anymore.

Additionally, the only kind of patches that I may be able to evaluate are those that aim to fix compilation issues with newer kernels. I can't test if a performance or compatibility fix is valid or not.

My suggestion would be to create a separate fork and maybe also rename the project to r8168-ce or something along that line.
